### ISSUE TITLE
IndependentActionCard不支持@人功能

### ISSUE THREAD

**Issue by DreamPWJ** [thierryxing/dingtalk-bot#4]
![image](https://user-images.githubusercontent.com/16730031/132073900-6670a7a3-89bb-4bb8-a9b6-423a767cb626.png)
![image](https://user-images.githubusercontent.com/16730031/132073920-2a8c7ebc-b194-4ab7-b9e5-822ff31e9ea2.png)
不生效 @thierryxing thierryxing

**Comment by thierryxing** [comment]
好的，我看一下

**Comment by thierryxing** [comment]
看了一下官方文档，action card也不支持@
https://developers.dingtalk.com/document/robots/custom-robot-access/title-72m-8ag-pqw

**Comment by DreamPWJ** [comment]
![image](https://user-images.githubusercontent.com/16730031/132308892-a5705077-6eda-46b8-926f-2d59390dab29.png)
是支持的  这是我们其他语言实现的，但是现在有一个需要ruby实现的需求，不然要改shell实现了 @thierryxing

**Comment by thierryxing** [comment]
可能是官方文档没有更新，我试试 action card 是否支持 atMobiles 参数

**Comment by thierryxing** [comment]
@DreamPWJ 其它语言最终生成的消息体 JSON，能发我一个实际的例子吗？

**Comment by DreamPWJ** [comment]
> @DreamPWJ 其它语言最终生成的消息体 JSON，能发我一个实际的例子吗？

我这边也是分装后的使用，@功能参数应该和其他的是一样的    我用的是插件https://jenkinsci.github.io/dingtalk-plugin/guide/getting-started.html

**Comment by thierryxing** [comment]
> > @DreamPWJ 其它语言最终生成的消息体 JSON，能发我一个实际的例子吗？
> 
> 我这边也是分装后的使用，@功能参数应该和其他的是一样的 我用的是插件https://jenkinsci.github.io/dingtalk-plugin/guide/getting-started.html

可以了，已经提交，你试试

**Comment by DreamPWJ** [comment]
可以了 @thierryxing
